apiVersion: v1
kind: Service
metadata:
  name: test-app-mysql-clusterIP
  labels:
    app: test-app
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: test-app
  annotations:
    volume.beta.kubernetes.io/storage-class: "mysql-standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-mysql
  labels:
    app: test-app
spec:
  selector:
    matchLabels:
      app: test-app
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-app
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
